#!/usr/bin/env bash
# regen-base-patches.sh -- (re)generate patches/base/*.patch from the fork's
# stacked base series (checkpoints C1 -> C2 -> C3 -> C4 -> E1 -> C5).
#
# Each base patch is exported as the diff of its checkpoint against the
# previous checkpoint.  This assumes the fork stack already sits on the
# target NVIDIA tag.  Rebasing the stack onto a NEW upstream tag (the
# tag-bump path) is intentionally NOT implemented here -- see
# docs/superpowers/specs/2026-05-22-dynamic-patch-composition-design.md.
#
# Usage: regen-base-patches.sh [--fork DIR] [--tag TAG]
#   --fork  default: $FORK_REPO or /root/open-gpu-kernel-modules
#   --tag   default: NVIDIA_OPEN_TAG from the injector Dockerfile
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
. "$repo_root/tools/lib/manifest.sh"

fork="${FORK_REPO:-/root/open-gpu-kernel-modules}"
tag=""
while [ $# -gt 0 ]; do
    case "$1" in
        --fork) fork="$2"; shift 2 ;;
        --tag)  tag="$2"; shift 2 ;;
        *) echo "regen: unknown arg '$1'" >&2; exit 2 ;;
    esac
done
[ -n "$tag" ] || tag="$(awk -F= '/^ARG NVIDIA_OPEN_TAG=/{print $2}' "$repo_root/Dockerfile")"
[ -n "$tag" ] || { echo "regen: could not determine target tag" >&2; exit 1; }
[ -d "$fork/.git" ] || { echo "regen: fork repo not found at $fork" >&2; exit 1; }

manifest="$repo_root/patches/manifest"
base_dir="$repo_root/patches/base"
mkdir -p "$base_dir"

tag_sha="$(git -C "$fork" rev-parse --verify "refs/tags/$tag^{commit}" 2>/dev/null)" \
    || { echo "regen: tag '$tag' not found in $fork" >&2; exit 1; }

state="$base_dir/.regen-state"
{
    echo "# regen-base-patches.sh state -- generated $(date -u +%FT%TZ)"
    echo "# base tag: $tag ($tag_sha)"
} > "$state"

prev_ref="$tag_sha"
prev_name="$tag"
count=0
while read -r id layer up src; do
    [ "$layer" = "base" ] || continue
    [ "$up" = "-" ] || continue          # upstreamed: nothing to generate
    case "$src" in
        fork:*) branch="${src#fork:}" ;;
        *) echo "regen: row '$id' has non-fork source '$src'" >&2; exit 1 ;;
    esac
    sha="$(git -C "$fork" rev-parse --verify "$branch^{commit}" 2>/dev/null)" \
        || { echo "regen: branch '$branch' not found in $fork" >&2; exit 1; }
    if ! git -C "$fork" merge-base --is-ancestor "$prev_ref" "$sha"; then
        echo "regen: '$branch' is not a descendant of '$prev_name'." >&2
        echo "       The fork stack is not in C1->...->C5 order on $tag, or it" >&2
        echo "       has not been rebased onto $tag. Rebase the fork stack" >&2
        echo "       manually first -- tag-bump rebasing is out of scope for" >&2
        echo "       this tool (see the design doc)." >&2
        exit 1
    fi
    out="$base_dir/$id.patch"
    {
        echo "# GENERATED by tools/regen-base-patches.sh -- DO NOT EDIT."
        echo "# Patch:  $id"
        echo "# Source: fork branch $branch @ $sha"
        echo "# Base:   $prev_name @ $prev_ref"
        echo "# Regenerate with: tools/regen-base-patches.sh"
        echo "#"
        git -C "$fork" diff "$prev_ref" "$sha"
    } > "$out"
    echo "$id  $branch  $sha" >> "$state"
    shortstat="$(git -C "$fork" diff --shortstat "$prev_ref" "$sha" | sed 's/^ *//')"
    echo "regen: wrote ${out#$repo_root/}  ($branch -- $shortstat)"
    prev_ref="$sha"
    prev_name="$branch"
    count=$((count + 1))
done <<EOF
$(manifest_rows "$manifest")
EOF

echo "regen: generated $count base patch(es) into ${base_dir#$repo_root/}/"

validate="$repo_root/tools/validate-patchset.sh"
if [ -x "$validate" ]; then
    echo "regen: validating composed set ..."
    "$validate"
else
    echo "regen: next -- run tools/validate-patchset.sh to compile-check the set."
fi
