#!/usr/bin/env bash
# render-patch-index.sh — generate docs/patch-index.md from the patch intents.
#
# Reads every <intents-dir>/*.md (excluding _template.md), extracts frontmatter
# and the first paragraph of `## Purpose`, and emits a single-table index.
# Row order follows the patches/manifest row order.
#
# Usage: render-patch-index.sh [--manifest FILE] [--intents-dir DIR] [--out FILE]
set -eu

here="$(cd "$(dirname "$0")" && pwd)"
. "$here/lib/intent.sh"

repo_root="$(cd "$here/.." && pwd)"
manifest="$repo_root/patches/manifest"
intents_dir="$repo_root/docs/patch-intents"
out="$repo_root/docs/patch-index.md"

while [ $# -gt 0 ]; do
    case "$1" in
        --manifest)    manifest="$2"; shift 2 ;;
        --intents-dir) intents_dir="$2"; shift 2 ;;
        --out)         out="$2"; shift 2 ;;
        -*) echo "render-patch-index: unknown flag '$1'" >&2; exit 2 ;;
        *)  echo "render-patch-index: unexpected arg '$1'" >&2; exit 2 ;;
    esac
done

# Extract the first non-blank paragraph of ## Purpose (one line, no surrounding ws).
purpose_summary() {
    awk '
        /^## Purpose[[:space:]]*$/ { inpurpose=1; next }
        inpurpose && /^## / { exit }
        inpurpose && NF > 0 { print; exit }
    ' "$1" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'
}

# Header.
{
    echo "# Patch index"
    echo
    echo "Generated by \`tools/render-patch-index.sh\` from \`docs/patch-intents/\`. Do not edit by hand."
    echo
    echo "| Id | Layer | Upstream candidacy | Telemetry | Status | Summary |"
    echo "|---|---|---|---|---|---|"
} > "$out"

# Iterate manifest rows; for each, find the intent file and emit a row.
grep -vE '^[[:space:]]*(#|$)' "$manifest" | while read -r mid layer up src; do
    intent="$intents_dir/$mid.md"
    if [ ! -f "$intent" ]; then
        printf '| %s | %s | — | — | — | (intent file missing) |\n' "$mid" "$layer" >> "$out"
        continue
    fi
    cand="$(intent_field "$intent" upstream-candidacy)"
    tel="$(intent_field "$intent" telemetry-tier)"
    status="$(intent_field "$intent" status)"
    summary="$(purpose_summary "$intent")"
    # Relative link from docs/patch-index.md to docs/patch-intents/<id>.md
    printf '| [%s](patch-intents/%s.md) | %s | %s | %s | %s | %s |\n' \
        "$mid" "$mid" "$layer" "$cand" "$tel" "$status" "$summary" >> "$out"
done

echo "render-patch-index: wrote ${out#$repo_root/}"
